# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PFXTimeTree' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for PFXTimeTree
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.4'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SwiftProgressHUD'
  pod 'CVCalendar', '~> 1.6.2'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  

  target 'PFXTimeTreeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PFXTimeTreeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
